### ISSUE TITLE
Build bases such as GTR

### ISSUE THREAD

**Issue by Astet0509** [Astet0509/chemie#4]
# Objective
Enable Chemie to build bases such as GTR if things don't get worse.

## Todo
- [ ] create a new base evaluater and make other evaluater use it internally.
- [ ] improve the way of evaluating.
- [ ] improve the way of searching.
